[model]
model_id = "bigscience/bloom-560m"
training_data_path = "src/data/train_data.json"

[lora_config]
r = 8
lora_alpha = 32
lora_dropout = 0.05
bias = "none"
task_type = "CAUSAL_LM"

[training_arguments]
per_device_train_batch_size = 1
gradient_accumulation_steps = 1
warmup_steps = 2
max_steps = -1
learning_rate = 2e-4
fp16 = true
logging_steps = 1
output_dir = "outputs"
optim = "paged_adamw_8bit"
remove_unused_columns = true

[meta]
adapter_path = 'vishakudupa/lora-resume-summary' #"thechashi/resume_summary_lora_bloom560m"
intro_blurb='''Go through the below resume thoroughly, and 
write a short summary of the resume and highlight the positive and 
negative aspects of the resume. Resume:'''
